export const ADD_COURS_REQUEST = "ADD_COURS_REQUEST";
export const ADD_COURS_SUCCESS = "ADD_COURS_SUCCESS";
export const ADD_COURS_FAILURE = "ADD_COURS_FAILURE";

// recuperation du cours

export const GET_COURS_FAILURE = "GET_COURS_FAILURE";
export const GET_ALL_COURS_REQUEST = "GET_ALL_COURS_REQUEST";
export const GET_ALL_COURS_SUCCESS = "GET_ALL_COURS_SUCCESS";

// suppression d'un cours
export const DELETE_COURS_REQUEST = "DELETE_COURS_REQUEST";
export const DELETE_COURS_SUCCESS = "DELETE_COURS_SUCCESS";

export const UPDATE_COURS_REQUEST = "UPDATE_COURS_REQUEST";
export const UPDATE_COURS_SUCCESS = "UPDATE_COURS_SUCCESS";
export const UPDATE_COURS_FAILLURE = "UPDATE_COURS_FAILLURE";
